// Generated by CoffeeScript 1.7.1
(function() {
  var Sandbox, child_process;

  child_process = require("child_process");

  Sandbox = (function() {
    function Sandbox(handler) {
      this.handler = handler;
      this.child = child_process.fork(__dirname + '/shovel.js');
      this.timer = 0;
      this.callback = this.handler;
      this.child.on("message", (function(_this) {
        return function(result) {
          clearTimeout(_this.timer);
          _this.callback(result);
          return _this.callback = _this.handler;
        };
      })(this));
    }

    Sandbox.prototype["eval"] = function(code, callback) {
      this.callback = callback;
      this.child.send(code);
      return this.timer = setTimeout(((function(_this) {
        return function() {
          _this.child.kill("SIGKILL");
          _this.callback("TimeoutError: restarting repl...");
          return _this.constructor.apply(_this);
        };
      })(this)), 10 * 1000);
    };

    return Sandbox;

  })();

  module.exports = Sandbox;

}).call(this);

//# sourceMappingURL=sandbox.map
