// Generated by CoffeeScript 1.6.3
(function() {
  var Sandbox, child_process;

  child_process = require("child_process");

  Sandbox = (function() {
    function Sandbox(handler) {
      var _this = this;
      this.handler = handler;
      this.child = child_process.fork(__dirname + '/shovel.js');
      this.timer = 0;
      this.callback = this.handler;
      this.child.on("message", function(result) {
        clearTimeout(_this.timer);
        _this.callback(result);
        return _this.callback = _this.handler;
      });
    }

    Sandbox.prototype["eval"] = function(code, callback) {
      var _this = this;
      this.callback = callback;
      this.child.send(code);
      return this.timer = setTimeout((function() {
        _this.child.kill("SIGKILL");
        _this.callback("TimeoutError: restarting repl...");
        return _this.constructor.apply(_this);
      }), 10 * 1000);
    };

    return Sandbox;

  })();

  module.exports = Sandbox;

}).call(this);
