// Generated by CoffeeScript 1.6.3
(function() {
  var Sandbox, cp;

  cp = require("child_process");

  Sandbox = (function() {
    function Sandbox(freetimeCB) {
      this.freetimeCB = freetimeCB != null ? freetimeCB : function() {};
      this.restart();
    }

    Sandbox.prototype.restart = function() {
      var _this = this;
      this.child = cp.fork(__dirname + '/shovel.js');
      this.cb = this.freetimeCB;
      this.timer = 0;
      return this.child.on("message", function(data) {
        clearTimeout(_this.timer);
        _this.cb(data);
        return _this.cb = _this.freetimeCB;
      });
    };

    Sandbox.prototype["eval"] = function(code, cb) {
      var _this = this;
      this.cb = cb;
      this.child.send(code);
      return this.timer = setTimeout((function() {
        _this.cb(["TimeoutError: restarting repl..."]);
        _this.child.kill("SIGKILL");
        return _this.restart();
      }), 10 * 1000);
    };

    return Sandbox;

  })();

  module.exports = Sandbox;

}).call(this);

/*
//@ sourceMappingURL=sandbox.map
*/
